# -----------------------------
#  Required settings
# -----------------------------
files:
  # File name to translate (must be placed under ./data/target/{lang})
  target_file: "example_nova.po"

# -----------------------------
#  Only for CI
# -----------------------------
git:
  # 1. Set project you want to translate
  project: "nova"
  # 2. Set targe_commit you want to translate
  target_commit: "d6f5a30caa1a4a139dc67272a150d24e44892a91"
  repo_url: "https://github.com/openstack/{project}.git"
  # path where cloning repository
  work_dir: "./workspace"

# -----------------------------
#  Common
# -----------------------------
languages:
  # When running local.sh, please choose exactly ONE language.
  # When running ci.sh, you can specify MULTIPLE languages.
  - "ko_KR"

# You can tune these arguments for performance / partial translation:
#   --model : Choose your model
#   --mode  : Choose your LLM mode[`ollama` (default, for open src LLM), `gpt`, `claude`, `gemini`]
#   --workers   : number of parallel threads (default: 1)
#   --start/end : entry index range to translate (default: 0 ~ all)
#   --batch-size: entries per LLM call (default: 5)
llm:
  model: "llama3.2:3b"
  mode: "ollama"
  workers: 1
  start: 0
  end: -1
  batch_size: 5

# Glossary: normally you don't need to edit this
glossary:
  url: "https://opendev.org/openstack/i18n/raw/commit/129b9de7be12740615d532591792b31566d0972f/glossary/locale/{lang}/LC_MESSAGES/glossary.po"

# Example: normally you don't need to edit this
examples:
  example_url: "https://opendev.org/openstack/nova/raw/branch/master/nova/locale/{lang}/LC_MESSAGES/nova.po"
  example_file: "nova-nova-locale.po"