# Set project you want to translate
project: "nova"

files:
  # Set target file path. Please put file under ./data/target/
  target_file: ".pot"

languages:
  - "ko_KR"

# You can tune these arguments for performance / partial translation:
#   --model : Choose your model
#   --mode  : Choose your LLM mode[`ollama` (default, for open src LLM), `gpt`, `claude`, `gemini`]
#   --workers   : number of parallel threads (default: 1)
#   --start/end : entry index range to translate (default: 0 ~ all)
#   --batch-size: entries per LLM call (default: 5)
llm:
  model: "llama3.2:3b"
  mode: "ollama"
  workers: 1
  start: 0
  end: -1
  batch_size: 5

# -----------------------------
# Glossary
# -----------------------------
glossary:
  url: "https://opendev.org/openstack/i18n/raw/commit/129b9de7be12740615d532591792b31566d0972f/glossary/locale/{lang}/LC_MESSAGES/glossary.po"

# -----------------------------
# Example
# -----------------------------
examples:
  example_url: "https://opendev.org/openstack/nova/raw/branch/master/nova/locale/{lang}/LC_MESSAGES/nova.po"
  example_file: "nova-nova-locale.po"

# -----------------------------
#  commit.diff.py (only for CI)
# -----------------------------
git:
  repo_url: "https://github.com/openstack/{project}.git"
  work_dir: "./workspace"

compare:
  # Set commit hash value you want to translate
  target_commit: "d6f5a30caa1a4a139dc67272a150d24e44892a91"



