git:
  repo_url: "https://github.com/openstack/nova.git"
  work_dir: "./workspace"
  repo_name: "nova"

compare:
  # 번역을 원하는 커밋 해시 값
  target_commit: "d6f5a30caa1a4a139dc67272a150d24e44892a91"
  base_commit: "HEAD~1"

output:
  pot_dir: "./pot"
  diff_filename: "diff.pot"

  # source_dir: pybabel이 스캔할 안쪽 폴더 (repo_name 내부 기준)
  # (전체를 스캔하고 싶으면 "." 을 입력)
  source_dir: "nova"